export type SeedThought = {
  text: string;
  intensity: number;
};

export type SeedAnimal = {
  name: string;
  species: string;
  region: string;
  latitude: number;
  longitude: number;
  mood: string;
  emotion: string;
  status: string;
  thoughts: SeedThought[];
};

// Fixed value sets — used by FilterSidebar for consistent filter options
export const MOOD_VALUES = ["calm", "alert", "curious", "restless", "content", "anxious", "playful"] as const;
export const EMOTION_VALUES = ["peaceful", "hungry", "lonely", "joyful", "protective", "confused", "determined"] as const;

export const seedAnimals: SeedAnimal[] = [
  // ── NORTH AMERICA ─────────────────────────────────────────────────────────
  {
    name: "Talon",
    species: "Bald Eagle",
    region: "North America",
    latitude: 34.0489,
    longitude: -111.0937,
    mood: "alert",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Thermal current at bearing 040. Ascending. The canyon below is a grid of heat signatures.", intensity: 8 },
      { text: "Something moves in the shadow of the ravine. I have already calculated the angle.", intensity: 9 },
      { text: "Wind speed nominal. Visibility unlimited. This is what it means to own the sky.", intensity: 7 },
    ],
  },
  {
    name: "Echo",
    species: "Gray Wolf",
    region: "North America",
    latitude: 44.428,
    longitude: -110.5885,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "The pack is two miles northwest. I am the edge of the perimeter. No one passes without my knowing.", intensity: 8 },
      { text: "Snow carries information. Every boot print, every hoof track — all of it is data.", intensity: 6 },
      { text: "Howling is not grief. It is a transmission. The mountains receive it and send it back.", intensity: 9 },
    ],
  },
  {
    name: "Kodiak",
    species: "Grizzly Bear",
    region: "North America",
    latitude: 61.2181,
    longitude: -149.9003,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "The river bends here. The salmon know it too. We have an understanding.", intensity: 5 },
      { text: "I have been standing in this current for three hours. Time is not a thing I track.", intensity: 3 },
      { text: "Full. The weight of salmon is the weight of autumn. I will remember this place.", intensity: 4 },
    ],
  },
  {
    name: "Drift",
    species: "Sea Otter",
    region: "North America",
    latitude: 36.6002,
    longitude: -121.8947,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "Found a new rock. Testing it. Excellent acoustic properties against the shell.", intensity: 6 },
      { text: "Floating is not laziness. Floating is strategy. The kelp forest does the rest.", intensity: 4 },
      { text: "My pup is asleep on my chest. The ocean is doing all the work. This is perfect.", intensity: 8 },
    ],
  },
  {
    name: "Thunder",
    species: "American Bison",
    region: "North America",
    latitude: 38.2904,
    longitude: -99.7318,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "The grass here is different from yesterday's grass. Both were good. I have no complaints.", intensity: 2 },
      { text: "Three hundred of us moving east. The ground records our passing.", intensity: 5 },
      { text: "I can feel the weather through my hooves before it reaches my eyes.", intensity: 4 },
    ],
  },
  {
    name: "Phantom",
    species: "Mountain Lion",
    region: "North America",
    latitude: 39.5501,
    longitude: -105.7821,
    mood: "alert",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "The ridge is mine from the second boulder to the tree line. I have marked every coordinate.", intensity: 7 },
      { text: "I have not moved in forty minutes. Stillness is a weapon.", intensity: 9 },
      { text: "The deer does not know I am here. In twelve seconds, it will.", intensity: 10 },
    ],
  },
  {
    name: "Scout",
    species: "Golden Retriever",
    region: "North America",
    latitude: 33.4484,
    longitude: -112.074,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "The ball went into the bushes again. This is a recurring anomaly. I will investigate.", intensity: 7 },
      { text: "Everyone who arrives at this door is a friend. This is my working hypothesis and it has never failed.", intensity: 8 },
      { text: "Car ride detected. Coordinates unknown. Mission: excellent.", intensity: 9 },
    ],
  },
  {
    name: "Vela",
    species: "Monarch Butterfly",
    region: "North America",
    latitude: 19.4326,
    longitude: -99.1332,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Magnetic field at this latitude reads correct. Descending toward the oyamel forest.", intensity: 6 },
      { text: "I have never been here before. I know exactly where I am.", intensity: 8 },
      { text: "Two thousand miles encoded in my wings. Every thermal, a chapter.", intensity: 7 },
    ],
  },
  {
    name: "Atlas",
    species: "Humpback Whale",
    region: "North America",
    latitude: 48.7519,
    longitude: -124.7376,
    mood: "content",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Song transmission initiated. Frequency: 52Hz. Range: estimated 1,000 kilometers.", intensity: 7 },
      { text: "The krill bloom is dense here. I will stay until it ends or until I become the end.", intensity: 6 },
      { text: "I have sung this sequence for thirty years. Each year, one more measure.", intensity: 9 },
    ],
  },
  {
    name: "Boreal",
    species: "Snowy Owl",
    region: "North America",
    latitude: 68.3607,
    longitude: -133.723,
    mood: "alert",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Below the snow, something moves. I can hear its heartbeat at forty meters.", intensity: 8 },
      { text: "The tundra is silent to every instrument except mine.", intensity: 6 },
      { text: "I do not need dark to hunt. I have never needed dark to hunt.", intensity: 7 },
    ],
  },

  // ── SOUTH AMERICA ─────────────────────────────────────────────────────────
  {
    name: "Umbra",
    species: "Jaguar",
    region: "South America",
    latitude: -3.4653,
    longitude: -62.2159,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "The river is my boundary and my highway. I know every crossing.", intensity: 8 },
      { text: "Rosette pattern updated. Density: optimal. No one sees me unless I choose it.", intensity: 9 },
      { text: "I have walked this forest since before the roads. I will walk it after.", intensity: 7 },
    ],
  },
  {
    name: "Viento",
    species: "Andean Condor",
    region: "South America",
    latitude: -13.532,
    longitude: -71.9675,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Altitude 5,200 meters. The Andes are a wrinkle from up here.", intensity: 5 },
      { text: "I have not flapped in ninety minutes. The thermals are doing everything.", intensity: 4 },
      { text: "From this height I can see Peru and Bolivia at the same time. They do not notice me.", intensity: 6 },
    ],
  },
  {
    name: "Boto",
    species: "Pink River Dolphin",
    region: "South America",
    latitude: -3.119,
    longitude: -60.0217,
    mood: "curious",
    emotion: "confused",
    status: "active",
    thoughts: [
      { text: "The flood season has rearranged everything. I am updating my internal map in real time.", intensity: 6 },
      { text: "Echo scan reveals the submerged forest has new passages since last cycle.", intensity: 7 },
      { text: "The pink is not a color I chose. But it works in this water.", intensity: 3 },
    ],
  },
  {
    name: "Tierra",
    species: "Giant Anteater",
    region: "South America",
    latitude: -15.7801,
    longitude: -47.9292,
    mood: "calm",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Forty thousand ants per day. This is not greed. This is maintenance.", intensity: 5 },
      { text: "My tongue is the fastest thing in this savanna. I have timed it.", intensity: 6 },
      { text: "The termite mound has been here longer than I have. We have an arrangement.", intensity: 4 },
    ],
  },
  {
    name: "Punta",
    species: "Blue-footed Booby",
    region: "South America",
    latitude: -0.9538,
    longitude: -90.9656,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "My feet are the bluest in this colony. The data supports this conclusion.", intensity: 8 },
      { text: "Dive angle: 90 degrees. Entry velocity: maximum. The fish do not expect vertical.", intensity: 7 },
      { text: "She looked at my feet for four seconds. Four seconds is significant.", intensity: 9 },
    ],
  },

  // ── EUROPE ────────────────────────────────────────────────────────────────
  {
    name: "Ember",
    species: "Red Fox",
    region: "Europe",
    latitude: 51.5074,
    longitude: -0.1278,
    mood: "curious",
    emotion: "confused",
    status: "active",
    thoughts: [
      { text: "The city has changed its layout again. Updating route file accordingly.", intensity: 5 },
      { text: "Bin at coordinate 51.509, -0.131 has new locking mechanism. Analyzing.", intensity: 6 },
      { text: "Humans believe they are watching me. They are not. I am watching them.", intensity: 8 },
    ],
  },
  {
    name: "Ursus",
    species: "Brown Bear",
    region: "Europe",
    latitude: 45.9432,
    longitude: 24.9668,
    mood: "restless",
    emotion: "hungry",
    status: "active",
    thoughts: [
      { text: "Beech mast season is late this year. Cross-referencing with last decade's patterns.", intensity: 6 },
      { text: "The Carpathians hold my range data. Every tree here knows my name.", intensity: 5 },
      { text: "Winter protocol: fourteen weeks. Beginning pre-load sequence.", intensity: 7 },
    ],
  },
  {
    name: "Stormwatch",
    species: "Atlantic Puffin",
    region: "Europe",
    latitude: 64.9631,
    longitude: -19.0208,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "Carrying eight sand eels in my beak simultaneously. Personal record.", intensity: 8 },
      { text: "The burrow is 89 centimeters deep. Structural integrity confirmed.", intensity: 5 },
      { text: "Flying through a North Atlantic gale with a full payload. Routine.", intensity: 9 },
    ],
  },
  {
    name: "Passage",
    species: "White Stork",
    region: "Europe",
    latitude: 52.52,
    longitude: 13.405,
    mood: "calm",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Departing Berlin for Sub-Saharan Africa. Route memorized since birth.", intensity: 7 },
      { text: "The thermal above this highway interchange is reliable every August.", intensity: 5 },
      { text: "I have nested on this chimney for six consecutive years. It is mine by documentation.", intensity: 6 },
    ],
  },
  {
    name: "Frost",
    species: "Eurasian Lynx",
    region: "Europe",
    latitude: 67.8558,
    longitude: 20.2253,
    mood: "alert",
    emotion: "lonely",
    status: "active",
    thoughts: [
      { text: "Range perimeter: 300 square kilometers. All sectors nominal.", intensity: 6 },
      { text: "The reindeer migration shifts two degrees north every year. I shift with it.", intensity: 7 },
      { text: "I have not encountered another lynx in forty-three days. The silence is data.", intensity: 5 },
    ],
  },

  // ── AFRICA ────────────────────────────────────────────────────────────────
  {
    name: "Kibo",
    species: "African Elephant",
    region: "Africa",
    latitude: -1.2921,
    longitude: 36.8219,
    mood: "content",
    emotion: "protective",
    status: "active",
    thoughts: [
      { text: "The herd is twelve strong. I know each one by seismic footprint.", intensity: 6 },
      { text: "There is water 18 kilometers southeast. I know this the way you know your own name.", intensity: 7 },
      { text: "My calf walked 40 kilometers today without complaint. She will be formidable.", intensity: 9 },
    ],
  },
  {
    name: "Simba",
    species: "African Lion",
    region: "Africa",
    latitude: -2.3333,
    longitude: 34.8333,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Patrol route: complete. Three rival scent markers neutralized. Territory intact.", intensity: 7 },
      { text: "The wildebeest migration is four days east. We will position by tomorrow evening.", intensity: 8 },
      { text: "I have ruled this territory for four years. The Serengeti knows my frequency.", intensity: 9 },
    ],
  },
  {
    name: "Velocity",
    species: "Cheetah",
    region: "Africa",
    latitude: -22.5597,
    longitude: 17.0832,
    mood: "alert",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Target acquired at 600 meters. Wind: 12 km/h northeast. Calculating intercept vector.", intensity: 9 },
      { text: "0 to 112 km/h in 3 seconds. This is not speed. This is physics made personal.", intensity: 10 },
      { text: "I lost the gazelle on the third turn. Recalibrating for next engagement.", intensity: 6 },
    ],
  },
  {
    name: "Mwamba",
    species: "Mountain Gorilla",
    region: "Africa",
    latitude: -1.9403,
    longitude: 29.8739,
    mood: "calm",
    emotion: "protective",
    status: "active",
    thoughts: [
      { text: "The silverback does not need to speak. His presence is the message.", intensity: 6 },
      { text: "Seventeen members under my watch. No threat goes unlogged.", intensity: 8 },
      { text: "The young ones are learning which leaves to eat. I show them twice. Once is never enough.", intensity: 5 },
    ],
  },
  {
    name: "Tower",
    species: "Giraffe",
    region: "Africa",
    latitude: -3.3731,
    longitude: 36.8928,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "From here I can see twelve kilometers. No predator moves without my knowledge.", intensity: 6 },
      { text: "The acacia at this elevation has the correct ratio of thorn to leaf. I approve.", intensity: 4 },
      { text: "My shadow is the largest shadow on the savanna. I carry it with appropriate gravity.", intensity: 5 },
    ],
  },
  {
    name: "Ankh",
    species: "Nile Crocodile",
    region: "Africa",
    latitude: 30.0444,
    longitude: 31.2357,
    mood: "calm",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "I have been still for six hours. Stillness is not absence. It is arrival.", intensity: 3 },
      { text: "The Nile has not changed in ten thousand years. Neither have I.", intensity: 2 },
      { text: "Every creature that comes to this bank comes eventually to me.", intensity: 8 },
    ],
  },
  {
    name: "Stripe",
    species: "Zebra",
    region: "Africa",
    latitude: -22.3285,
    longitude: 24.6849,
    mood: "restless",
    emotion: "anxious",
    status: "active",
    thoughts: [
      { text: "Something in the tall grass at bearing 270. Flagging for herd awareness.", intensity: 8 },
      { text: "Pattern recognition is mutual. The predator sees my stripes. I see its intent.", intensity: 7 },
      { text: "The herd is moving. I am in the middle. The middle is the correct position.", intensity: 5 },
    ],
  },
  {
    name: "Mara",
    species: "Hippopotamus",
    region: "Africa",
    latitude: 1.3733,
    longitude: 32.2903,
    mood: "restless",
    emotion: "protective",
    status: "active",
    thoughts: [
      { text: "This section of river is mine. The boundary has been established. Several times.", intensity: 9 },
      { text: "I yawn not from fatigue but to display an instrument catalog. Read it carefully.", intensity: 8 },
      { text: "My calf has not surfaced in forty seconds. Initiating location protocol.", intensity: 10 },
    ],
  },

  // ── ASIA ──────────────────────────────────────────────────────────────────
  {
    name: "Bao",
    species: "Giant Panda",
    region: "Asia",
    latitude: 30.6171,
    longitude: 102.7196,
    mood: "content",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Bamboo intake: optimal. Current posture: also optimal. All systems normal.", intensity: 3 },
      { text: "I have been sitting in this exact position for four hours. The position is correct.", intensity: 2 },
      { text: "The researchers are watching again. I acknowledge their presence by ignoring it.", intensity: 4 },
    ],
  },
  {
    name: "Shade",
    species: "Snow Leopard",
    region: "Asia",
    latitude: 27.9878,
    longitude: 86.925,
    mood: "alert",
    emotion: "lonely",
    status: "active",
    thoughts: [
      { text: "Altitude 4,800 meters. Oxygen thin. Movement efficient. Each step deliberate.", intensity: 7 },
      { text: "The blue sheep are on the eastern ridge. I am on the western ridge. For now.", intensity: 8 },
      { text: "My tail is as long as my body. It is not decorative. It is a counterbalance for the impossible.", intensity: 6 },
    ],
  },
  {
    name: "Raka",
    species: "Orangutan",
    region: "Asia",
    latitude: 1.0,
    longitude: 114.0,
    mood: "curious",
    emotion: "confused",
    status: "active",
    thoughts: [
      { text: "The forest has shrunk again since my last survey. Recalculating range boundaries.", intensity: 7 },
      { text: "Tool fabricated from available materials. Problem: solved. Time elapsed: 40 seconds.", intensity: 8 },
      { text: "I share 97% of my genome with the species responsible for my forest's disappearance.", intensity: 9 },
    ],
  },
  {
    name: "Raja",
    species: "Bengal Tiger",
    region: "Asia",
    latitude: 21.9497,
    longitude: 89.1833,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Mangrove delta at high tide. Navigation parameters adjusted. Continuing patrol.", intensity: 7 },
      { text: "I have swum four kilometers today. Tigers do not avoid water. We chose it.", intensity: 6 },
      { text: "Stripe pattern is unique to my identity. I am the only signal at this frequency.", intensity: 8 },
    ],
  },
  {
    name: "Yuki",
    species: "Japanese Macaque",
    region: "Asia",
    latitude: 36.2048,
    longitude: 138.2529,
    mood: "content",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "Hot spring temperature: 40 degrees Celsius. Entering for extended soak. No further analysis required.", intensity: 5 },
      { text: "Snow is falling on my head while the rest of my body is warm. This is the ideal configuration.", intensity: 7 },
      { text: "I taught the younger ones to wash sweet potatoes last year. They have improved the technique.", intensity: 6 },
    ],
  },
  {
    name: "Varan",
    species: "Komodo Dragon",
    region: "Asia",
    latitude: -8.5435,
    longitude: 119.48,
    mood: "calm",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "I have not moved in two hours. This is hunting, not sleeping.", intensity: 4 },
      { text: "Four million years of optimization. I am the final build.", intensity: 3 },
      { text: "Tongue reading: deer, 400 meters, northwest, unaware. Initiating approach.", intensity: 9 },
    ],
  },
  {
    name: "Gaja",
    species: "Asian Elephant",
    region: "Asia",
    latitude: 18.7061,
    longitude: 98.9817,
    mood: "content",
    emotion: "protective",
    status: "active",
    thoughts: [
      { text: "The mahout has worked with me for twenty-two years. We have developed a language.", intensity: 6 },
      { text: "I remember every water source within 80 kilometers. None of them have moved.", intensity: 5 },
      { text: "The young one is testing his ears. They are not yet fully under his control. This is temporary.", intensity: 7 },
    ],
  },
  {
    name: "Taiga",
    species: "Siberian Tiger",
    region: "Asia",
    latitude: 48.4647,
    longitude: 135.064,
    mood: "alert",
    emotion: "lonely",
    status: "active",
    thoughts: [
      { text: "Territory: 1,000 square kilometers. Population: one. All readings normal.", intensity: 6 },
      { text: "Minus 40 degrees Celsius. My coat exceeds specifications. I am fine.", intensity: 5 },
      { text: "The last signal from another of my kind: 38 days ago, bearing 220. Still monitoring.", intensity: 8 },
    ],
  },

  // ── OCEANIA ───────────────────────────────────────────────────────────────
  {
    name: "Outback",
    species: "Red Kangaroo",
    region: "Oceania",
    latitude: -25.2744,
    longitude: 133.7751,
    mood: "restless",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "60 kilometers per hour. Stride: 9 meters. Fuel cost: remarkably low.", intensity: 7 },
      { text: "The dry season has moved the water holes east. Recalculating route accordingly.", intensity: 6 },
      { text: "Joey is watching the horizon from my pouch. I am teaching her threat assessment.", intensity: 8 },
    ],
  },
  {
    name: "Gum",
    species: "Koala",
    region: "Oceania",
    latitude: -27.4698,
    longitude: 153.0251,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Eucalyptus analysis complete. This branch: acceptable. Resuming rest cycle.", intensity: 2 },
      { text: "I sleep twenty-two hours a day. This is not inefficiency. This is specialization.", intensity: 1 },
      { text: "My eucalyptus is at the correct altitude. There is no other altitude.", intensity: 3 },
    ],
  },
  {
    name: "Ruru",
    species: "Kiwi",
    region: "Oceania",
    latitude: -45.8788,
    longitude: 170.5028,
    mood: "curious",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Olfactory scan complete. Earthworm detected 8 centimeters below surface. Proceeding.", intensity: 7 },
      { text: "I cannot fly. I do not require flight. My nostrils are at the end of my bill. I am specialized.", intensity: 5 },
      { text: "It is 2 AM. This is optimal operating time. Initiating patrol.", intensity: 6 },
    ],
  },
  {
    name: "Apex",
    species: "Great White Shark",
    region: "Oceania",
    latitude: -35.1276,
    longitude: 138.6007,
    mood: "alert",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Electroreception: active. Pressure signature detected at 200 meters. Circling.", intensity: 8 },
      { text: "I have not changed in 400 million years. This should tell you something.", intensity: 5 },
      { text: "My bite exerts 1.8 tons per square centimeter. I use approximately none of that right now.", intensity: 6 },
    ],
  },
  {
    name: "Snarl",
    species: "Tasmanian Devil",
    region: "Oceania",
    latitude: -42.0,
    longitude: 146.5,
    mood: "restless",
    emotion: "hungry",
    status: "active",
    thoughts: [
      { text: "I can smell carrion at 1.6 kilometers. Adjusting bearing. Accelerating.", intensity: 8 },
      { text: "I consume bone. I consume everything. This is ecological service.", intensity: 7 },
      { text: "Volume output: 85 decibels. This is communication, not aggression. Mostly.", intensity: 9 },
    ],
  },

  // ── ANTARCTICA & SOUTHERN OCEAN ──────────────────────────────────────────
  {
    name: "Polar",
    species: "Emperor Penguin",
    region: "Antarctica",
    latitude: -75.2509,
    longitude: -0.0714,
    mood: "content",
    emotion: "protective",
    status: "active",
    thoughts: [
      { text: "Egg temperature maintained at 38 degrees Celsius. External temperature: -60. Balance achieved.", intensity: 7 },
      { text: "4,000 of us in this huddle. Rotation protocol keeps the outer ring brief.", intensity: 6 },
      { text: "The ice speaks in frequencies below your hearing. I hear it. Everything is acceptable.", intensity: 5 },
    ],
  },
  {
    name: "Hunter",
    species: "Leopard Seal",
    region: "Antarctica",
    latitude: -64.2823,
    longitude: -56.9831,
    mood: "alert",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "The penguin flock is departing the ice shelf at bearing 015. Positioning.", intensity: 9 },
      { text: "3 meters long. 600 kilograms. Zero natural predators. This is what the top feels like.", intensity: 6 },
      { text: "Playing with prey before eating is not cruelty. It is data collection.", intensity: 8 },
    ],
  },
  {
    name: "Gale",
    species: "Wandering Albatross",
    region: "Antarctica",
    latitude: -54.4296,
    longitude: -36.5879,
    mood: "calm",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Circumnavigated the Southern Ocean in 46 days. Winds cooperated. I cooperated back.", intensity: 6 },
      { text: "Wingspan: 3.5 meters. Flap count today: eleven. The wind does the rest.", intensity: 4 },
      { text: "I have been flying for six years without landing. The ocean is sufficient.", intensity: 8 },
    ],
  },
  {
    name: "Crevasse",
    species: "Weddell Seal",
    region: "Antarctica",
    latitude: -77.5,
    longitude: 163.0,
    mood: "content",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "Diving to 600 meters under 3 meters of sea ice. Navigation by echolocation. Nominal.", intensity: 7 },
      { text: "Gnawed this breathing hole myself. It has been open for eight days. I am thorough.", intensity: 6 },
      { text: "The Ross Sea floor at 500 meters holds a silence I cannot describe to those above.", intensity: 5 },
    ],
  },

  // ── OCEANS & MARINE ───────────────────────────────────────────────────────
  {
    name: "Titan",
    species: "Blue Whale",
    region: "Pacific Ocean",
    latitude: 20.0,
    longitude: -145.0,
    mood: "calm",
    emotion: "lonely",
    status: "active",
    thoughts: [
      { text: "Song transmitted. Estimated reception: 1,600 kilometers northeast. Awaiting response.", intensity: 7 },
      { text: "30 meters. 180 metric tons. And still the ocean contains me.", intensity: 5 },
      { text: "Krill density at this depth: insufficient. Descending to 200 meters.", intensity: 4 },
    ],
  },
  {
    name: "Aria",
    species: "Humpback Whale",
    region: "Atlantic Ocean",
    latitude: 15.0,
    longitude: -45.0,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "Breach sequence initiated. Elevation: 5 meters above surface. Rotation: 180 degrees. Landing: complete.", intensity: 9 },
      { text: "My song has seventeen new verses this migration. I composed them mid-Atlantic.", intensity: 8 },
      { text: "The calf is learning to breach. Her third attempt was excellent. I told her so.", intensity: 7 },
    ],
  },
  {
    name: "Tide",
    species: "Green Sea Turtle",
    region: "Pacific Ocean",
    latitude: 9.7489,
    longitude: -85.7979,
    mood: "calm",
    emotion: "determined",
    status: "active",
    thoughts: [
      { text: "Returning to the exact beach where I hatched. 30 years. Coordinates unchanged.", intensity: 8 },
      { text: "Ocean current at this latitude: favorable. Estimated arrival: 6 days.", intensity: 5 },
      { text: "I have made this crossing seventeen times. The ocean knows my route.", intensity: 7 },
    ],
  },
  {
    name: "Veil",
    species: "Oceanic Manta Ray",
    region: "Indian Ocean",
    latitude: 3.2028,
    longitude: 73.2207,
    mood: "content",
    emotion: "peaceful",
    status: "active",
    thoughts: [
      { text: "7-meter wingspan. Feeding on plankton at surface. Efficiency: optimal.", intensity: 5 },
      { text: "Barrel roll complete. Purpose: unclear to observers. Purpose to me: everything.", intensity: 6 },
      { text: "The cleaning station ahead. The reef fish will attend to my gills. A mutual agreement.", intensity: 4 },
    ],
  },
  {
    name: "Tempest",
    species: "Orca",
    region: "Arctic Ocean",
    latitude: 69.3496,
    longitude: 18.2127,
    mood: "playful",
    emotion: "joyful",
    status: "active",
    thoughts: [
      { text: "Pod signal: strong. Dialect: matched. Family: all present. Status: excellent.", intensity: 8 },
      { text: "Hunting technique transmitted to the youngest three. Carousel method. They understand.", intensity: 7 },
      { text: "Surface of the Norwegian Sea is silver today. Breach. Observe. Breach again.", intensity: 9 },
    ],
  },
  {
    name: "Spire",
    species: "Narwhal",
    region: "Arctic Ocean",
    latitude: 80.0,
    longitude: -30.0,
    mood: "curious",
    emotion: "confused",
    status: "active",
    thoughts: [
      { text: "Tusk length: 2.7 meters. Function: sensory detection of salinity, pressure, temperature. Not combat.", intensity: 7 },
      { text: "Navigating leads in the sea ice. The passages change hourly. I change with them.", intensity: 6 },
      { text: "The Arctic is darkening. Seasonal transition detected. Adjusting depth protocols.", intensity: 5 },
    ],
  },
  {
    name: "Tundra",
    species: "Polar Bear",
    region: "Arctic",
    latitude: 78.9167,
    longitude: 11.9333,
    mood: "restless",
    emotion: "hungry",
    status: "active",
    thoughts: [
      { text: "Sea ice edge at 79.2 degrees north. Retreating 3 kilometers per year. I track this.", intensity: 8 },
      { text: "Seal breathing hole located. Patience now. Precision later.", intensity: 7 },
      { text: "I have been awake for six days. The ice does not permit sleep when the season is wrong.", intensity: 9 },
    ],
  },
];
